version: "3"

# Global variables
vars:
  REGISTRY: ghcr.io
  IMAGE_REPO: "github.io/faboulaye/gitops-canary-demo"
  NAMESPACE: apps
  PY: python
  PIP: pip
  GIT_COMMIT:
    sh: git rev-parse HEAD
  APP_VERSION:
    sh: echo "$(git describe --tags --abbrev=0 2>/dev/null || echo 0.0.0)-$(git rev-parse --short HEAD)"

# Run: task <name>
tasks:
  default:
    desc: Show common tasks
    cmds:
      - task -l

  # ---------- Local dev ----------
  deps:
    desc: Install local Python deps
    run: once
    cmds:
      - |
        {{.PIP}} install --upgrade pip
      - |
        {{.PIP}} install -r app/requirements.txt -r requirements-dev.txt

  run:
    desc: Run the app locally
    deps: [deps]
    interactive: true
    env:
      APP_VERSION: "{{.APP_VERSION}}"
      GIT_COMMIT: "{{.GIT_COMMIT}}"
    cmds:
      - |
        {{.PY}} -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8080

  test:
    desc: Run unit tests with pytest
    deps: [deps]
    cmds:
      - |
        {{.PY}} -m pytest -vv
