namespace: apps

image:
  repository: ghcr.io/faboulaye/gitops-canary-demo
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  host: argo-cd.faboulaye.dev
